* Vagrant sinatra with proxy example

Keywords: vagrant rbenv ruby sinatra mysql ActiveRecord god systemd proxy

This is a simple Vagrant configuration that works behind our corporate
proxy.

Based on Ubuntu 16.04 (Xenial), it shows how to install =ruby= (using
=rbenv=), =sinatra=, =ActiveRecord= and =mysql= server. The configuration also
shows how to start your application server automatically when the
machine boots using the =god= monitoring tool which is itself managed by
=systemd=.

See the [[file:provision/][provision/]] directory for the shell scripts used in the vagrant
provisioning phase.

The [[./monitor/][monitor/]] directory contains the scripts for managing the server at
runtime.

** Usage

*** Host: Start vagrant

#+begin_src sh
vagrant up
#+end_src

The [[file:./Vagrantfile][Vagrantfile]] will detect whether you're behind a proxy by testing
whether the =https_proxy= environment variable exists. If it does, the
instance will be configured to use the same proxy. If not, the proxy
setting code is bypassed.

If you change networks, you can reconfigure with:

#+begin_src sh
vagrant reload --provision
#+end_src

The provisioning phase will run the scripts in the [[file:provision/][provision/]]
directory to install packages, =rbenv=, =ruby= and will run =bundle install=
in your application directory.

*** Host: Test app

On the host, browse to http://127.0.0.1:8000

You should see the text:

: [{"id":1,"name":"Rick"},{"id":2,"name":"Morty"}]

*** Host: Shell into vagrant guest instance

#+begin_src sh
vagrant ssh
#+end_src

*** Host: Manage sinatra app

The application is started automatically in the provisioning phase by
using the =god= monitoring tool (which itself is managed by =systemd= -
see [[file:./provision/fs/etc/systemd/system/god.service][god.service]]).

The =god= configuration is in [[file:sinatra.god][sinatra.god]].

**** To get the current status of the app

#+begin_src sh
monitor/status
#+end_src

**** To restart the app

e.g. after changing [[file:bin/app.rb][bin/app.rb]]

#+begin_src sh
monitor/restart
#+end_src

**** To stop the app

#+begin_src sh
monitor/stop
#+end_src

** Mysql configuration

The Vagrantfile defines the following environment variables used by
the =mysql= installation and =ActiveRecord= (in [[file:bin/app.rb][bin/app.rb]]).

| Var                 | Example   |
|---------------------+-----------|
| MYSQL_ROOT_PASSWORD | root123   |
| MYSQL_APP_HOST      | localhost |
| MYSQL_APP_DB        | appdb     |
| MYSQL_APP_USERNAME  | appuser   |
| MYSQL_APP_PASSWORD  | user123   |
